use crossterm::event::{KeyEvent, MouseEvent};

#[derive(Debug, Clone)]
/// `Event` is an enum that represents the different types of events that can be generated by the
/// intraction with the terminal (`tui_backend`).
/// These events are used to drive the user interface and the application logic and should be handled entirely.
pub enum Event {
  Init,
  Quit,
  Render,
  Key(KeyEvent),
  Mouse(MouseEvent),
  Resize(u16, u16),
}
